---
# tasks file for my_project
# tasks/main.yml
- name: Install the httpd package
  ansible.builtin.dnf:
    name: httpd
    state: present

- name: Ensure the httpd service is running
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes

- name: Copy the custom index.html page
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
    owner: apache
    group: apache
  notify:
    - Restart httpd service

